-- Migration: Move all metadata fields to dedicated columns
-- This migration adds all metadata fields as columns and migrates existing data

-- ============================================
-- STEP 1: Add new columns to Post table
-- ============================================

-- Article fields
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "language" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "isPublished" BOOLEAN;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "articleId" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "fullArticle" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "articleCategory" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "subCategoryId" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "subCategory" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "chapterId" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "section" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "headline" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "quickViewContent" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "targetedKeywords" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "autoGeneratedKeywords" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "articleDate" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "eventDates" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "eventYearRange" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "locationLat" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "locationLong" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "district" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "sendNotification" BOOLEAN;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "notificationTime" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "articleType" TEXT;

-- Job fields
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "companyName" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "selectRole" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "jobLocation" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "clientToManage" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "workingDays" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "yearlySalary" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "salaryMin" INTEGER;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "salaryMax" INTEGER;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "skills" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "jobFunction" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "experience" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "jobType" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "capacity" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "workTime" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "perksAndBenefits" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "candidateQualities" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "isPublic" BOOLEAN;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "isPrivate" BOOLEAN;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "privateFiltersCollege" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "privateFiltersCourse" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "privateFiltersCourseCategory" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "privateFiltersYear" TEXT;

-- ============================================
-- STEP 2: Migrate data from metadata to columns
-- ============================================

-- Migrate article fields
UPDATE "Post"
SET 
  "language" = CASE 
    WHEN metadata->>'language' = 'ENGLISH' THEN 'ENGLISH'
    WHEN metadata->>'language' = 'HINDI' THEN 'HINDI'
    ELSE NULL
  END,
  "isPublished" = CASE 
    WHEN metadata->>'isPublished' IS NOT NULL THEN (metadata->>'isPublished')::boolean
    ELSE NULL
  END,
  "articleId" = metadata->>'articleId',
  "fullArticle" = metadata->>'fullArticle',
  "articleCategory" = metadata->>'category',
  "subCategoryId" = metadata->>'subCategoryId',
  "subCategory" = metadata->>'subCategory',
  "chapterId" = metadata->>'chapterId',
  "section" = metadata->>'section',
  "country" = metadata->>'country',
  "headline" = metadata->>'headline',
  "quickViewContent" = metadata->>'quickViewContent',
  "targetedKeywords" = metadata->>'targetedKeywords',
  "autoGeneratedKeywords" = metadata->>'autoGeneratedKeywords',
  "articleDate" = metadata->>'date',
  "eventDates" = CASE 
    WHEN metadata->'eventDates' IS NOT NULL AND jsonb_typeof(metadata->'eventDates') = 'array' 
    THEN ARRAY(SELECT jsonb_array_elements_text(metadata->'eventDates'))
    ELSE ARRAY[]::TEXT[]
  END,
  "eventYearRange" = metadata->>'eventYearRange',
  "locationLat" = metadata->'location'->>'lat',
  "locationLong" = metadata->'location'->>'long',
  "state" = metadata->>'state',
  "district" = metadata->>'district',
  "city" = metadata->>'city',
  "sendNotification" = CASE 
    WHEN metadata->>'sendNotification' IS NOT NULL THEN (metadata->>'sendNotification')::boolean
    ELSE NULL
  END,
  "notificationTime" = metadata->>'notificationTime',
  "articleType" = metadata->>'type'
WHERE metadata IS NOT NULL;

-- Migrate job fields
UPDATE "Post"
SET 
  "companyName" = metadata->>'companyName',
  "industry" = metadata->>'industry',
  "selectRole" = metadata->>'selectRole',
  "jobLocation" = metadata->>'location',
  "clientToManage" = metadata->>'clientToManage',
  "workingDays" = metadata->>'workingDays',
  "yearlySalary" = metadata->>'yearlySalary',
  "salaryMin" = CASE 
    WHEN metadata->>'salaryMin' IS NOT NULL THEN (metadata->>'salaryMin')::integer
    ELSE NULL
  END,
  "salaryMax" = CASE 
    WHEN metadata->>'salaryMax' IS NOT NULL THEN (metadata->>'salaryMax')::integer
    ELSE NULL
  END,
  "skills" = CASE 
    WHEN metadata->'skills' IS NOT NULL AND jsonb_typeof(metadata->'skills') = 'array' 
    THEN ARRAY(SELECT jsonb_array_elements_text(metadata->'skills'))
    ELSE ARRAY[]::TEXT[]
  END,
  "jobFunction" = metadata->>'function',
  "experience" = metadata->>'experience',
  "jobType" = CASE 
    WHEN metadata->>'jobType' = 'Full-time' THEN 'FULL_TIME'
    WHEN metadata->>'jobType' = 'Part-time' THEN 'PART_TIME'
    WHEN metadata->>'jobType' = 'Contract' THEN 'CONTRACT'
    WHEN metadata->>'jobType' = 'Internship' THEN 'INTERNSHIP'
    WHEN metadata->>'jobType' = 'Freelance' THEN 'FREELANCE'
    ELSE NULL
  END,
  "capacity" = metadata->>'capacity',
  "workTime" = metadata->>'workTime',
  "perksAndBenefits" = metadata->>'perksAndBenefits',
  "candidateQualities" = CASE 
    WHEN metadata->'candidateQualities' IS NOT NULL AND jsonb_typeof(metadata->'candidateQualities') = 'array' 
    THEN ARRAY(SELECT jsonb_array_elements_text(metadata->'candidateQualities'))
    ELSE ARRAY[]::TEXT[]
  END,
  "isPublic" = CASE 
    WHEN metadata->>'isPublic' IS NOT NULL THEN (metadata->>'isPublic')::boolean
    ELSE NULL
  END,
  "isPrivate" = CASE 
    WHEN metadata->>'isPrivate' IS NOT NULL THEN (metadata->>'isPrivate')::boolean
    ELSE NULL
  END,
  "privateFiltersCollege" = metadata->'privateFilters'->>'selectCollege',
  "privateFiltersCourse" = metadata->'privateFilters'->>'selectCourse',
  "privateFiltersCourseCategory" = metadata->'privateFilters'->>'selectCourseCategory',
  "privateFiltersYear" = metadata->'privateFilters'->>'selectYear'
WHERE metadata IS NOT NULL AND "postType" = 'JOB';

-- Set articleId to post id for articles (if not already set)
UPDATE "Post"
SET "articleId" = id
WHERE ("postType" = 'CURRENT_AFFAIRS' OR "postType" = 'COLLEGE_FEED')
  AND "articleId" IS NULL;

-- ============================================
-- STEP 3: Add columns to McqQuestion table
-- ============================================

ALTER TABLE "McqQuestion" ADD COLUMN IF NOT EXISTS "mcqCategory" TEXT;
ALTER TABLE "McqQuestion" ADD COLUMN IF NOT EXISTS "subCategory" TEXT;
ALTER TABLE "McqQuestion" ADD COLUMN IF NOT EXISTS "subCategoryId" TEXT;
ALTER TABLE "McqQuestion" ADD COLUMN IF NOT EXISTS "chapterId" TEXT;
ALTER TABLE "McqQuestion" ADD COLUMN IF NOT EXISTS "section" TEXT;
ALTER TABLE "McqQuestion" ADD COLUMN IF NOT EXISTS "country" TEXT;
ALTER TABLE "McqQuestion" ADD COLUMN IF NOT EXISTS "questionImage" TEXT;
ALTER TABLE "McqQuestion" ADD COLUMN IF NOT EXISTS "explanationImage" TEXT;

-- Migrate MCQ metadata
UPDATE "McqQuestion"
SET 
  "mcqCategory" = metadata->>'category',
  "subCategory" = metadata->>'subCategory',
  "subCategoryId" = metadata->>'subCategoryId',
  "chapterId" = metadata->>'chapterId',
  "section" = metadata->>'section',
  "country" = metadata->>'country',
  "questionImage" = metadata->>'questionImage',
  "explanationImage" = metadata->>'explanationImage'
WHERE metadata IS NOT NULL;

-- ============================================
-- STEP 4: Create indexes for performance
-- ============================================

-- Article indexes
CREATE INDEX IF NOT EXISTS "idx_posts_language" ON "Post"("language") WHERE "language" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_is_published" ON "Post"("isPublished") WHERE "isPublished" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_article_id" ON "Post"("articleId") WHERE "articleId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_sub_category_id" ON "Post"("subCategoryId") WHERE "subCategoryId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_chapter_id" ON "Post"("chapterId") WHERE "chapterId" IS NOT NULL;

-- Job indexes
CREATE INDEX IF NOT EXISTS "idx_posts_job_type" ON "Post"("jobType") WHERE "postType" = 'JOB' AND "jobType" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_is_public" ON "Post"("isPublic") WHERE "postType" = 'JOB' AND "isPublic" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_is_private" ON "Post"("isPrivate") WHERE "postType" = 'JOB' AND "isPrivate" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_industry" ON "Post"("industry") WHERE "postType" = 'JOB' AND "industry" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_job_function" ON "Post"("jobFunction") WHERE "postType" = 'JOB' AND "jobFunction" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_salary_min" ON "Post"("salaryMin") WHERE "postType" = 'JOB' AND "salaryMin" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_posts_salary_max" ON "Post"("salaryMax") WHERE "postType" = 'JOB' AND "salaryMax" IS NOT NULL;

-- MCQ indexes
CREATE INDEX IF NOT EXISTS "idx_mcq_sub_category_id" ON "McqQuestion"("subCategoryId") WHERE "subCategoryId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_mcq_chapter_id" ON "McqQuestion"("chapterId") WHERE "chapterId" IS NOT NULL;

-- ============================================
-- STEP 5: Add check constraints for enums
-- ============================================

-- Note: Prisma will handle enum constraints when we run prisma migrate
-- But we can add explicit checks for data integrity

ALTER TABLE "Post" ADD CONSTRAINT "check_language" CHECK ("language" IS NULL OR "language" IN ('ENGLISH', 'HINDI'));
ALTER TABLE "Post" ADD CONSTRAINT "check_job_type" CHECK ("jobType" IS NULL OR "jobType" IN ('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', 'FREELANCE'));
ALTER TABLE "Post" ADD CONSTRAINT "check_private_filters_year" CHECK ("privateFiltersYear" IS NULL OR "privateFiltersYear" IN ('1', '2', '3', '4'));

