import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsOptional, IsBoolean, IsArray, IsDateString, IsEnum } from 'class-validator';

export enum Language {
  ENGLISH = 'ENGLISH',
  HINDI = 'HINDI',
}

export class CreateArticleDto {
  @ApiProperty({ description: 'Article title' })
  @IsString()
  @IsNotEmpty()
  title: string;

  @ApiProperty({ description: 'Article description (max 60 words)' })
  @IsString()
  @IsNotEmpty()
  // Note: Word count validation is done in service after stripping HTML
  description: string;

  @ApiProperty({ description: 'Language (ENGLISH | HINDI)', enum: Language, required: false })
  @IsEnum(Language)
  @IsOptional()
  language?: Language;

  @ApiProperty({ description: 'Category ID', required: false })
  @IsString()
  @IsOptional()
  categoryId?: string;

  @ApiProperty({ description: 'Images', type: [String], required: false })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  images?: string[];

  @ApiProperty({ description: 'Is active', required: false })
  @IsBoolean()
  @IsOptional()
  isActive?: boolean;

  @ApiProperty({ description: 'Is published', required: false })
  @IsBoolean()
  @IsOptional()
  isPublished?: boolean;

  // Article-specific fields (moved from metadata)
  @ApiProperty({ description: 'Full article content', required: false })
  @IsString()
  @IsOptional()
  fullArticle?: string;

  @ApiProperty({ description: 'Category name (denormalized)', required: false })
  @IsString()
  @IsOptional()
  articleCategory?: string;

  @ApiProperty({ description: 'Sub category ID (UUID)', required: false })
  @IsString()
  @IsOptional()
  subCategoryId?: string;

  @ApiProperty({ description: 'Sub category name', required: false })
  @IsString()
  @IsOptional()
  subCategory?: string;

  @ApiProperty({ description: 'Chapter ID (UUID)', required: false })
  @IsString()
  @IsOptional()
  chapterId?: string;

  @ApiProperty({ description: 'Section', required: false })
  @IsString()
  @IsOptional()
  section?: string;

  @ApiProperty({ description: 'Country', required: false })
  @IsString()
  @IsOptional()
  country?: string;

  @ApiProperty({ description: 'Headline', required: false })
  @IsString()
  @IsOptional()
  headline?: string;

  @ApiProperty({ description: 'Quick view content (max 60 words)', required: false })
  @IsString()
  @IsOptional()
  quickViewContent?: string;

  @ApiProperty({ description: 'Targeted keywords', required: false })
  @IsString()
  @IsOptional()
  targetedKeywords?: string;

  @ApiProperty({ description: 'Auto generated keywords', required: false })
  @IsString()
  @IsOptional()
  autoGeneratedKeywords?: string;

  @ApiProperty({ description: 'Article date (YYYY-MM-DD)', required: false })
  @IsDateString()
  @IsOptional()
  articleDate?: string;

  @ApiProperty({ description: 'Event dates', type: [String], required: false })
  @IsArray()
  @IsDateString({}, { each: true })
  @IsOptional()
  eventDates?: string[];

  @ApiProperty({ description: 'Event year range', required: false })
  @IsString()
  @IsOptional()
  eventYearRange?: string;

  @ApiProperty({ description: 'Location latitude', required: false })
  @IsString()
  @IsOptional()
  locationLat?: string;

  @ApiProperty({ description: 'Location longitude', required: false })
  @IsString()
  @IsOptional()
  locationLong?: string;

  @ApiProperty({ description: 'State', required: false })
  @IsString()
  @IsOptional()
  state?: string;

  @ApiProperty({ description: 'District', required: false })
  @IsString()
  @IsOptional()
  district?: string;

  @ApiProperty({ description: 'City', required: false })
  @IsString()
  @IsOptional()
  city?: string;

  @ApiProperty({ description: 'Send notification', required: false })
  @IsBoolean()
  @IsOptional()
  sendNotification?: boolean;

  @ApiProperty({ description: 'Notification time (HH:MM)', required: false })
  @IsString()
  @IsOptional()
  notificationTime?: string;

  @ApiProperty({ description: 'Article type (GENERAL_KNOWLEDGE for GK articles)', required: false })
  @IsString()
  @IsOptional()
  articleType?: string;
}


