import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsOptional, IsBoolean, IsArray, IsDateString, IsEnum, ValidateIf, ValidateNested, Matches } from 'class-validator';
import { Type } from 'class-transformer';

export enum Language {
  ENGLISH = 'ENGLISH',
  HINDI = 'HINDI',
}

export class EventDateDto {
  @ApiProperty({ description: 'Event date in MM-DD format', example: '01-26' })
  @IsString()
  @IsNotEmpty()
  @Matches(/^(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])$/, {
    message: 'Date must be in MM-DD format (e.g., 01-26)',
  })
  date: string;

  @ApiProperty({ description: 'Event title', example: 'Republic Day Reminder' })
  @IsString()
  @IsNotEmpty()
  title: string;
}

export class CreateArticleDto {
  @ApiProperty({ description: 'Article title' })
  @IsString()
  @IsNotEmpty()
  title: string;

  @ApiProperty({ 
    description: 'Article description. Can contain HTML formatting. HTML tags are preserved and stored as-is.',
    example: '<p>Brief description with <strong>bold</strong> text.</p>'
  })
  @IsString()
  @IsNotEmpty()
  description: string;

  @ApiProperty({ description: 'Language (ENGLISH | HINDI)', enum: Language, required: false })
  @IsEnum(Language)
  @IsOptional()
  language?: Language;

  @ApiProperty({ description: 'Category ID', required: false })
  @IsString()
  @IsOptional()
  categoryId?: string;

  @ApiProperty({ description: 'Images', type: [String], required: false })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  images?: string[];

  @ApiProperty({ description: 'Is active', required: false })
  @IsBoolean()
  @IsOptional()
  isActive?: boolean;

  @ApiProperty({ description: 'Is published', required: false })
  @IsBoolean()
  @IsOptional()
  isPublished?: boolean;

  // Article-specific fields (moved from metadata)
  @ApiProperty({ 
    description: 'Full article content as HTML string. HTML tags are preserved and stored as-is. Example: "<h2>Title</h2><p>Content with <strong>bold</strong> text.</p>"', 
    required: false,
    example: '<h2>Article Title</h2><p>This is <strong>bold</strong> and <em>italic</em> text.</p><ul><li>Item 1</li><li>Item 2</li></ul>'
  })
  @IsString()
  @IsOptional()
  fullArticle?: string;

  @ApiProperty({ description: 'Category name (denormalized)', required: false })
  @IsString()
  @IsOptional()
  articleCategory?: string;

  @ApiProperty({ description: 'Sub category ID (UUID)', required: false })
  @IsString()
  @IsOptional()
  subCategoryId?: string;

  @ApiProperty({ description: 'Sub category name', required: false })
  @IsString()
  @IsOptional()
  subCategory?: string;

  @ApiProperty({ description: 'Chapter ID (UUID)', required: false })
  @IsString()
  @IsOptional()
  chapterId?: string;

  @ApiProperty({ description: 'Section', required: false })
  @IsString()
  @IsOptional()
  section?: string;

  @ApiProperty({ description: 'Country', required: false })
  @IsString()
  @IsOptional()
  country?: string;

  @ApiProperty({ description: 'Headline', required: false })
  @IsString()
  @IsOptional()
  headline?: string;

  @ApiProperty({ description: 'Quick view content (max 60 words)', required: false })
  @IsString()
  @IsOptional()
  quickViewContent?: string;

  @ApiProperty({ description: 'Targeted keywords', required: false })
  @IsString()
  @IsOptional()
  targetedKeywords?: string;

  @ApiProperty({ description: 'Auto generated keywords', required: false })
  @IsString()
  @IsOptional()
  autoGeneratedKeywords?: string;

  @ApiProperty({ description: 'Article date (YYYY-MM-DD)', required: false })
  @IsDateString()
  @IsOptional()
  articleDate?: string;

  @ApiProperty({ 
    description: 'Event dates array with date and title', 
    type: [EventDateDto], 
    required: false,
    example: [{ date: '01-26', title: 'Republic Day Reminder' }, { date: '08-15', title: 'Independence Day' }]
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => EventDateDto)
  eventDates?: EventDateDto[];

  @ApiProperty({ description: 'Event year range', required: false })
  @IsString()
  @IsOptional()
  eventYearRange?: string;

  @ApiProperty({ description: 'Location latitude', required: false })
  @IsString()
  @IsOptional()
  locationLat?: string;

  @ApiProperty({ description: 'Location longitude', required: false })
  @IsString()
  @IsOptional()
  locationLong?: string;

  @ApiProperty({ description: 'State', required: false })
  @IsString()
  @IsOptional()
  state?: string;

  @ApiProperty({ description: 'District', required: false })
  @IsString()
  @IsOptional()
  district?: string;

  @ApiProperty({ description: 'City', required: false })
  @IsString()
  @IsOptional()
  city?: string;

  @ApiProperty({ description: 'Send notification', required: false })
  @IsBoolean()
  @IsOptional()
  sendNotification?: boolean;

  @ApiProperty({ description: 'Notification time (HH:MM)', required: false })
  @IsString()
  @IsOptional()
  notificationTime?: string;

  @ApiProperty({ description: 'Article type (GENERAL_KNOWLEDGE for GK articles)', required: false })
  @IsString()
  @IsOptional()
  articleType?: string;
}


