import { ApiProperty } from '@nestjs/swagger';
import { IsString, IsNotEmpty, IsOptional, IsBoolean, IsArray, IsObject, ValidateNested, IsDateString, IsNumber, Min, Max, MaxLength } from 'class-validator';
import { Type } from 'class-transformer';

class LocationDto {
  @ApiProperty({ description: 'Latitude', example: 28.6139 })
  @IsNumber()
  @Min(-90)
  @Max(90)
  lat: number;

  @ApiProperty({ description: 'Longitude', example: 77.2090 })
  @IsNumber()
  @Min(-180)
  @Max(180)
  long: number;
}

class ArticleMetadataDto {
  @ApiProperty({ description: 'Full article content', required: false })
  @IsString()
  @IsOptional()
  fullArticle?: string;

  @ApiProperty({ description: 'Category', required: false })
  @IsString()
  @IsOptional()
  category?: string;

  @ApiProperty({ description: 'Sub category', required: false })
  @IsString()
  @IsOptional()
  subCategory?: string;

  @ApiProperty({ description: 'Section', required: false })
  @IsString()
  @IsOptional()
  section?: string;

  @ApiProperty({ description: 'Country', required: false })
  @IsString()
  @IsOptional()
  country?: string;

  @ApiProperty({ description: 'Post type', example: 'General Knowledge' })
  @IsString()
  @IsOptional()
  postType?: string;

  @ApiProperty({ description: 'Headline', required: false })
  @IsString()
  @IsOptional()
  headline?: string;

  @ApiProperty({ description: 'Quick view content (max 60 words)', required: false })
  @IsString()
  @IsOptional()
  quickViewContent?: string;

  @ApiProperty({ description: 'Targeted keywords', required: false })
  @IsString()
  @IsOptional()
  targetedKeywords?: string;

  @ApiProperty({ description: 'Auto generated keywords', required: false })
  @IsString()
  @IsOptional()
  autoGeneratedKeywords?: string;

  @ApiProperty({ description: 'Article date (YYYY-MM-DD)', required: false })
  @IsDateString()
  @IsOptional()
  date?: string;

  @ApiProperty({ description: 'Event dates', type: [String], required: false })
  @IsArray()
  @IsDateString({}, { each: true })
  @IsOptional()
  eventDates?: string[];

  @ApiProperty({ description: 'Event year range', required: false })
  @IsString()
  @IsOptional()
  eventYearRange?: string;

  @ApiProperty({ description: 'Location coordinates', type: LocationDto, required: false })
  @IsObject()
  @ValidateNested()
  @Type(() => LocationDto)
  @IsOptional()
  location?: LocationDto;

  @ApiProperty({ description: 'State', required: false })
  @IsString()
  @IsOptional()
  state?: string;

  @ApiProperty({ description: 'District', required: false })
  @IsString()
  @IsOptional()
  district?: string;

  @ApiProperty({ description: 'City', required: false })
  @IsString()
  @IsOptional()
  city?: string;

  @ApiProperty({ description: 'Send notification', required: false })
  @IsBoolean()
  @IsOptional()
  sendNotification?: boolean;

  @ApiProperty({ description: 'Notification time (HH:MM)', required: false })
  @IsString()
  @IsOptional()
  notificationTime?: string;

  @ApiProperty({ description: 'Article ID for MCQ linking', required: false })
  @IsString()
  @IsOptional()
  articleId?: string;
}

export class CreateArticleDto {
  @ApiProperty({ description: 'Article title' })
  @IsString()
  @IsNotEmpty()
  title: string;

  @ApiProperty({ description: 'Article description (max 60 words)' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(500) // Approximate max for 60 words
  description: string;

  @ApiProperty({ description: 'Category ID', required: false })
  @IsString()
  @IsOptional()
  categoryId?: string;

  @ApiProperty({ description: 'Images', type: [String], required: false })
  @IsArray()
  @IsString({ each: true })
  @IsOptional()
  images?: string[];

  @ApiProperty({ description: 'Is active', required: false })
  @IsBoolean()
  @IsOptional()
  isActive?: boolean;

  @ApiProperty({ description: 'Is published', required: false })
  @IsBoolean()
  @IsOptional()
  isPublished?: boolean;

  @ApiProperty({ description: 'Article metadata', type: ArticleMetadataDto, required: false })
  @IsObject()
  @ValidateNested()
  @Type(() => ArticleMetadataDto)
  @IsOptional()
  metadata?: ArticleMetadataDto;
}


